Skeleton ReadMe
KristinJJ/Cranidores pull request #73
Opened 2023-05-01 21:18 UTC by brandondombrowsky

2023-05-01 23:08 UTC, KristinJJ requested changes
Hi Brandon, this draft of the ReadMe is looking good! I like the explanations of the different sections. One request I have is to correct the spelling of "Acknowledgements". Thanks!

2023-05-02 14:25 UTC, KristinJJ reviewed
Hi Brandon, just looked at this again since I have fresh eyes. Is my name meant to be in the team section twice? ![image](https://user-images.githubusercontent.com/26866132/235695804-dd817e6d-a980-4a50-a3a8-4e0a1a4bf2a7.png) ![image](https://user-images.githubusercontent.com/26866132/235695862-77a74566-6ab9-4f53-bc92-6ad9d5c96090.png) 

Also not sure if the alignment of the bullet points being indented is intentional or not.

2023-05-05 03:40 UTC, KristinJJ approved these changes

2023-05-05 03:52 UTC, ariunzayaE approved these changes
LGTM

2023-05-05 03:52 UTC, merged